### ISSUE TITLE
Making Plant Growth Faster

### ISSUE THREAD

**Issue by StealthFPS** [UntouchedWagons/Plant-Growth-Accelerator#1]
I suggest a config option or new block that is even faster than the Plant Growth Accelerator. Right now with about 250 accelerators stacked on top of each other it is still not growing super fast. I would recommend having a config option to change the speed or a new block like the Diamond Plant Growth Accelerator which would have a crafting recipe with a diamond above a normal accelerator which doubles or triples the speed of the original accelerator.

**Comment by UntouchedWagons** [comment]
A tower of accelerators only has a 1/64 chance of accelerating a plant's growth every tick. Also, some plants don't grow every single time they're ticked. Cactus and sugar cane for example need to be ticked 16 times before their growth advances. Some plants like Ender Lily seeds have a special mechanic like checking if it's daytime and other stuff which I don't plan to mess around with. If you want plants to grow extremely fast, you can stack the effects of Thaumcraft's Lamp of Growth, OpenBlocks' sprinkler, MFR's fertilizer and one of Blood Magic's rites. What I'm getting at is I don't see a problem with the way it is now.

**Comment by StealthFPS** [comment]
Alright, I was just thinking if you can make a block with a higher change of accelerating growth.

Date: Wed, 8 Apr 2015 13:35:28 -0700
